### ISSUE TITLE
Unhandled exception rendering component: Could not find 'ChartJsInterop' in 'window'.       Error: Could not find 'ChartJsInterop' in 'window'.

### ISSUE THREAD

**Issue by manish** [mariusmuntean/ChartJs.Blazor#142]
### Describe the bug

Cannot add data points to LineChart using netcore 3.1 blazor project. Get an error `Unhandled exception rendering component: Could not find 'ChartJsInterop' in 'window'.       Error: Could not find 'ChartJsInterop' in 'window'.`

Running on Chrome  `84.0.4147.89 (Official Build) (64-bit)` on macOS.

### Which Blazor project type is your bug related to?

- Client-Side

### Which charts does this bug apply to?

LineChart

### To Reproduce

1. Install `2.0.0-preview1`
2. Copy-paste the code from https://github.com/mariusmuntean/ChartJs.Blazor/blob/master/samples/Shared/ChartJs.Blazor.Sample.Shared/Components/LineChart/LinearLineChartComponent.razor
3. Instead of data being populated on initialization, change it to being initialized on some button click.
4. Click on the button and let the chart update.

### Expected behavior

The line chart is rendered.

### Screenshots
![image](https://user-images.githubusercontent.com/16161/89216631-bd8b7500-d598-11ea-8f56-914362b49492.png)

### Additional context / logging
Add any additional context about the problem here.

```batch
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not find 'ChartJsInterop' in 'window'.
      Error: Could not find 'ChartJsInterop' in 'window'.
          at https://localhost:5001/_framework/blazor.webassembly.js:1:9130
          at Array.forEach (<anonymous>)
          at p (https://localhost:5001/_framework/blazor.webassembly.js:1:9090)
          at https://localhost:5001/_framework/blazor.webassembly.js:1:9800
          at new Promise (<anonymous>)
          at Object.beginInvokeJSFromDotNet (https://localhost:5001/_framework/blazor.webassembly.js:1:9773)
          at _mono_wasm_invoke_js_marshalled (https://localhost:5001/_framework/wasm/dotnet.3.2.0.js:1:171294)
          at do_icall (https://localhost:5001/_framework/wasm/dotnet.wasm:wasm-function[6049]:0x10f8b1)
          at do_icall_wrapper (https://localhost:5001/_framework/wasm/dotnet.wasm:wasm-function[1896]:0x50b6a)
          at interp_exec_method (https://localhost:5001/_framework/wasm/dotnet.wasm:wasm-function[1120]:0x2588e)
Microsoft.JSInterop.JSException: Could not find 'ChartJsInterop' in 'window'.
Error: Could not find 'ChartJsInterop' in 'window'.
    at https://localhost:5001/_framework/blazor.webassembly.js:1:9130
    at Array.forEach (<anonymous>)
    at p (https://localhost:5001/_framework/blazor.webassembly.js:1:9090)
    at https://localhost:5001/_framework/blazor.webassembly.js:1:9800
    at new Promise (<anonymous>)
    at Object.beginInvokeJSFromDotNet (https://localhost:5001/_framework/blazor.webassembly.js:1:9773)
    at _mono_wasm_invoke_js_marshalled (https://localhost:5001/_framework/wasm/dotnet.3.2.0.js:1:171294)
    at do_icall (https://localhost:5001/_framework/wasm/dotnet.wasm:wasm-function[6049]:0x10f8b1)
    at do_icall_wrapper (https://localhost:5001/_framework/wasm/dotnet.wasm:wasm-function[1896]:0x50b6a)
    at interp_exec_method (https://localhost:5001/_framework/wasm/dotnet.wasm:wasm-function[1120]:0x2588e)
  at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask (System.Threading.Tasks.Task taskToHandle) <0x475fe20 + 0x000b6> in <filename unknown>:0 
```
### Code example

`GetDataAsync` fetching data can be replaced with any random number generator.
 
```csharp
<button type="button" class="btn btn-primary" @onclick="GetDataAsync">Go</button>
@if (MetricData != null && MetricData.Any())
	{
		<div class="row form-row mt-4 justify-content-center">
			<Chart @ref="_lineChartJs"
				   Config="@_lineConfig"
				   TConfig="LineConfig"
				   Width="600"
				   Height="300" />
		</div>
	}

@code
{
protected override Task OnInitializedAsync()
    {
        _lineConfig = new LineConfig
        {
            Options = new LineOptions
            {
                Responsive = true,
                Title = new OptionsTitle
                {
                    Display = true,
                    Text = "Line Chart"
                },
                Legend = new Legend
                {
                    Position = Position.Right,
                    Labels = new LegendLabels
                    {
                        UsePointStyle = true
                    }
                },
                Tooltips = new Tooltips
                {
                    Mode = InteractionMode.Nearest,
                    Intersect = false
                },
                Scales = new Scales
                {
                    XAxes = new List<CartesianAxis>
                {
                        new LinearCartesianAxis
                        {
                            ScaleLabel = new ScaleLabel
                            {
                                LabelString = "Time"
                            },
                            GridLines = new GridLines
                            {
                                Display = false
                            },
                            Ticks = new LinearCartesianTicks
                            {
                                SuggestedMin = -2
                            }
                        }
                    },
                    YAxes = new List<CartesianAxis>
                {
                        new LinearCartesianAxis
                        {
                            ScaleLabel = new ScaleLabel
                            {
                                LabelString = "Temp"
                            },
                            Ticks = new LinearCartesianTicks
                            {
                                Callback = new DelegateHandler<AxisTickCallback>(DegreesTickCallback)
                            }
                        }
                    }
                },
                Hover = new Hover
                {
                    Intersect = true,
                    Mode = InteractionMode.Y
                }
            }
        };
        actualValueSet = new LineDataset<Point>
        {
            BackgroundColor = ColorUtil.ColorString(0, 255, 0, 1.0),
            BorderColor = ColorUtil.ColorString(0, 0, 255, 1.0),
            Label = "Temp (C) per Hour",
            Fill = false,
            PointBackgroundColor = ColorUtil.RandomColorString(),
            BorderWidth = 1,
            PointRadius = 3,
            PointBorderWidth = 1,
            SteppedLine = SteppedLine.False,
        };
        _lineConfig.Data.Datasets.Add(actualValueSet);

        return base.OnInitializedAsync();
    }

    public async Task GetDataAsync()
    {
        foreach((int x, int y) in new[] { (1, 3), (2, 4), (3, 12), (4, 23), (5, 2) })
        {
            var point = new Point(x, y);
            Log.Information("Found point: {@Point}", point);
            actualValueSet.Add(point);
        }
        //await _lineChartJs.Update();
    }

    LineConfig _lineConfig;
    Chart<LineConfig> _lineChartJs;
    private LineDataset<Point> actualValueSet;
}
```

**Comment by Joelius300** [comment]
Did you follow the instructions in the readme and add the necessary script tags to your `index.html`?

```
<!-- Reference the included moment.js javascript file. -->
<script src="_content/ChartJs.Blazor/moment-with-locales.min.js" type="text/javascript" language="javascript"></script>

<!-- Reference the included ChartJs javascript file. -->
<script src="_content/ChartJs.Blazor/Chart.min.js" type="text/javascript" language="javascript"></script>

<!-- This is the glue between the C# code and the ChartJs charts -->
<script src="_content/ChartJs.Blazor/ChartJsBlazorInterop.js" type="text/javascript" language="javascript"></script>

<!-- Some styling -->
<link rel="stylesheet" href="_content/ChartJs.Blazor/ChartJSBlazor.css" />
```

**Comment by manish** [comment]
Oops. I realize it now. This diff was in the git stash. 

Sorry about the hassle. I am closing the bug.
