### ISSUE TITLE
Unhandled Exception during build with latest previews

### ISSUE THREAD

**Issue by RoyRosenberg** [mariusmuntean/ChartJs.Blazor#29]
Hi,
After adding ChartJs.Blazor package to my Blazor client project, I got this error during build:
Unhandled Exception: Mono.Linker.MarkException: Error processing method: 'System.Void ChartJs.Blazor.ChartJS.Common.Legends.OnHover.DotNetInstanceHoverHandler::.ctor(ChartJs.Blazor.ChartJS.Common.Legends.OnHover.DotNetInstanceHoverHandler/LegendItemOnHover)' in assembly: 'ChartJs.Blazor.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void Microsoft.JSInterop.DotNetObjectRef::.ctor(System.Object)
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at Mono.Linker.Driver.Run(ILogger customLogger)
   at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
   at Mono.Linker.Driver.Main(String[] args)

Using:

- VS 2019 Preview 2.0 (16.2.0)
- Net Core 3.0 Preview 
- ChartJs.Blazor 0.9.1-preview
- Blazor 3.0.0-preview6.19307.2

How can it be solved?
10x!

**Comment by SeppPenner** [comment]
If I was you, I would take a look at https://github.com/Joelius300/ChartJSBlazor. This project is maintained at least.

**Comment by Joelius300** [comment]
I have not seen this issue occur since updating .NET and Blazor. Since it's also quite an old issue without activity in the last few months, I'm closing this issue. If the issue persists, feel free to reopen it :)
